### ISSUE TITLE
ImportError: undefined symbol: _mkdir

### ISSUE THREAD

**Issue by ldesousa** [asselapathirana/swmm5-python#2]
I have now successfully compiled and installed swmm5-python. However, it fails immediately on import:

```
>>> from swmm5.swmm5tools import SWMM5Simulation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/SWMM5-5.1.0.102-py2.7-linux-x86_64.egg/swmm5/swmm5tools.py", line 1, in <module>
    from . import swmm5
  File "/usr/local/lib/python2.7/dist-packages/SWMM5-5.1.0.102-py2.7-linux-x86_64.egg/swmm5/swmm5.py", line 28, in <module>
    _swmm5 = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/SWMM5-5.1.0.102-py2.7-linux-x86_64.egg/swmm5/swmm5.py", line 20, in swig_import_helper
    import _swmm5
ImportError: /usr/local/lib/python2.7/dist-packages/SWMM5-5.1.0.102-py2.7-linux-x86_64.egg/_swmm5.so: undefined symbol: _mkdir
```

No real clue on where is this coming from. A missing dependency perhaps? There is no requirements file, I therefore assume the programme should run independently.

Thank you.

**Comment by asselapathirana** [comment]
This seems to be an issue with older SWMM version. Should not be an issue with the current version (see: https://stackoverflow.com/questions/43269227/linux-undefined-symbol-mkdir-in-the-so-file-of-swmm5-python-package)
